/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_natives_WinUtil */

#ifndef _Included_org_sikuli_natives_WinUtil
#define _Included_org_sikuli_natives_WinUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    switchApp
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_natives_WinUtil_switchApp__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    switchApp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_natives_WinUtil_switchApp__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    openApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_natives_WinUtil_openApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    closeApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_natives_WinUtil_closeApp__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    closeApp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_natives_WinUtil_closeApp__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    bringWindowToFront
 * Signature: (Ljava/awt/Window;Z)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_natives_WinUtil_bringWindowToFront
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    getHwnd
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_natives_WinUtil_getHwnd__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    getHwnd
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_natives_WinUtil_getHwnd__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    getRegion
 * Signature: (JI)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_natives_WinUtil_getRegion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sikuli_natives_WinUtil
 * Method:    getFocusedRegion
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_natives_WinUtil_getFocusedRegion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
