/*
 * Copyright (c) 2010-2018, sikuli.org, sikulix.com - MIT license
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.natives.finder;

public class FindInput {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FindInput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FindInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VisionProxyJNI.delete_FindInput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FindInput() {
    this(VisionProxyJNI.new_FindInput__SWIG_0(), true);
  }

  public void setTarget(int target_type, String target_string) {
    VisionProxyJNI.FindInput_setTarget__SWIG_0(swigCPtr, this, target_type, target_string);
  }

  public void setTarget(Mat target) {
    VisionProxyJNI.FindInput_setTarget__SWIG_1(swigCPtr, this, Mat.getCPtr(target), target);
  }

  public void setSource(Mat source) {
    VisionProxyJNI.FindInput_setSource__SWIG_1(swigCPtr, this, Mat.getCPtr(source), source);
  }

  public void setFindAll(boolean all) {
    VisionProxyJNI.FindInput_setFindAll(swigCPtr, this, all);
  }

  public void setSimilarity(double similarity) {
    VisionProxyJNI.FindInput_setSimilarity(swigCPtr, this, similarity);
  }

}
