buttons = "buttons.png"
macButtonsChrome = "macButtonsChrome.png"
macButtonsSafari = "macButtonsSafari.png"
button = "button.png"
apple = "apple.png"
macButton = "macButton.png"
macApple = "macApple.png"
