#!/bin/sh
# creates the javadocs for selected classes and their public members
apijar=SetupAPI/target/sikulixsetupAPI-1.1.2-SNAPSHOT-forsetup.jar
apisrc=API/src/main/java/org/sikuli/script
basicssrc=API/src/main/java/org/sikuli/basics
echo $apisrc/Region.java >createJavadocsClasses
echo $apisrc/FindFailed.java >>createJavadocsClasses
echo $apisrc/Match.java >>createJavadocsClasses
echo $apisrc/Screen.java >>createJavadocsClasses
echo $apisrc/Pattern.java >>createJavadocsClasses
echo $apisrc/Location.java >>createJavadocsClasses
echo $apisrc/Image.java >>createJavadocsClasses
echo $apisrc/ImagePath.java >>createJavadocsClasses
echo $apisrc/ScreenImage.java >>createJavadocsClasses
echo $apisrc/Finder.java >>createJavadocsClasses
echo $apisrc/Mouse.java >>createJavadocsClasses
echo $apisrc/Button.java >>createJavadocsClasses
echo $apisrc/Key.java >>createJavadocsClasses
echo $apisrc/ObserverCallBack.java >>createJavadocsClasses
echo $apisrc/ObserveEvent.java >>createJavadocsClasses
echo $apisrc/App.java >>createJavadocsClasses
echo $apisrc/Env.java >>createJavadocsClasses
echo $basicssrc/Settings.java >>createJavadocsClasses
echo $basicssrc/Debug.java >>createJavadocsClasses
javadoc -public -classpath $apijar -d pages/javadocs @createJavadocsClasses
rm createJavadocsClasses
