#!/bin/bash

#if [ -e Setup/target/classes/content/SHOULDDEPLOY ]; then

  cd API;
  mvn deploy -B -P sign,build-extras -f deploy.xml --settings ../codesigning/mvnsettings.xml;
  cd ../SetupAPI;
  mvn deploy -B -P sign,build-extras -f deploy.xml --settings ../codesigning/mvnsettings.xml;
  cd ../SetupIDE;
  mvn deploy -B -P sign,build-extras -f deploy.xml --settings ../codesigning/mvnsettings.xml;
  cd ../Setup;
  mvn deploy -B -P sign,build-extras -f deploy.xml --settings ../codesigning/mvnsettings.xml;
  cd ..

#fi
