#!/bin/bash
if [ -e API/target/classes/setup/content/SHOULDDEPLOY ]; then

  echo ---------- deploy API to OSSRH
  cd API;
  mvn deploy -B -P sign,build-source,build-docs -f deploy.xml --settings ../codesigning/mvnsettings.xml;
  cd ..;

fi
