/*
 * Copyright (c) 2010-2017, sikuli.org, sikulix.com - MIT license
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.natives;

public class FindResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FindResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FindResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VisionProxyJNI.delete_FindResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    VisionProxyJNI.FindResult_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return VisionProxyJNI.FindResult_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    VisionProxyJNI.FindResult_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return VisionProxyJNI.FindResult_y_get(swigCPtr, this);
  }

  public void setW(int value) {
    VisionProxyJNI.FindResult_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return VisionProxyJNI.FindResult_w_get(swigCPtr, this);
  }

  public void setH(int value) {
    VisionProxyJNI.FindResult_h_set(swigCPtr, this, value);
  }

  public int getH() {
    return VisionProxyJNI.FindResult_h_get(swigCPtr, this);
  }

  public void setScore(double value) {
    VisionProxyJNI.FindResult_score_set(swigCPtr, this, value);
  }

  public double getScore() {
    return VisionProxyJNI.FindResult_score_get(swigCPtr, this);
  }

  public FindResult() {
    this(VisionProxyJNI.new_FindResult__SWIG_0(), true);
  }

  public FindResult(int _x, int _y, int _w, int _h, double _score) {
    this(VisionProxyJNI.new_FindResult__SWIG_1(_x, _y, _w, _h, _score), true);
  }

  public void setText(String value) {
    VisionProxyJNI.FindResult_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return VisionProxyJNI.FindResult_text_get(swigCPtr, this);
  }

}
