/*
 * Copyright (c) 2010-2017, sikuli.org, sikulix.com - MIT license
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.natives;

public class OCR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OCR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VisionProxyJNI.delete_OCR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void setParameter(String param, String value) {
    VisionProxyJNI.OCR_setParameter(param, value);
  }

  public OCR() {
    this(VisionProxyJNI.new_OCR(), true);
  }

}
