/*
 * Copyright (c) 2010-2017, sikuli.org, sikulix.com - MIT license
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.natives;

public class OCRLines {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OCRLines(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCRLines obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VisionProxyJNI.delete_OCRLines(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCRLines() {
    this(VisionProxyJNI.new_OCRLines__SWIG_0(), true);
  }

  public OCRLines(long n) {
    this(VisionProxyJNI.new_OCRLines__SWIG_1(n), true);
  }

  public long size() {
    return VisionProxyJNI.OCRLines_size(swigCPtr, this);
  }

  public long capacity() {
    return VisionProxyJNI.OCRLines_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    VisionProxyJNI.OCRLines_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return VisionProxyJNI.OCRLines_isEmpty(swigCPtr, this);
  }

  public void clear() {
    VisionProxyJNI.OCRLines_clear(swigCPtr, this);
  }

  public void add(OCRLine x) {
    VisionProxyJNI.OCRLines_add(swigCPtr, this, OCRLine.getCPtr(x), x);
  }

  public OCRLine get(int i) {
    return new OCRLine(VisionProxyJNI.OCRLines_get(swigCPtr, this, i), false);
  }

  public void set(int i, OCRLine val) {
    VisionProxyJNI.OCRLines_set(swigCPtr, this, i, OCRLine.getCPtr(val), val);
  }

}
