/*
 * Copyright (c) 2010-2017, sikuli.org, sikulix.com - MIT license
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.natives;

public final class TARGET_TYPE {
  public final static int MAT = 0;
  public final static int IMAGE = MAT + 1;
  public final static int TEXT = IMAGE + 1;
  public final static int BUTTON = TEXT + 1;
}
