#!/bin/sh
echo ------- uploading API and IDE jars

apijar=`ls API/target/sikulixapi*complete.jar`
cp $apijar pages/sikulixapi.jar

apisrcjar=`ls API/target/sikulixapi*sources.jar`
cp $apisrcjar pages/sikulixapi-sources.jar

idejar=`ls IDE/target/sikulixide*complete.jar`
cp $idejar pages/sikulix.jar

echo ------ updating downloads page

jar=`ls API/target/sikulixapi*complete.jar`
build=`java -jar $apijar buildDate`

echo "s/##sikulixapiide##/$build/" >sedcommand
echo "s/##TRAVIS_BUILD_NUMBER##/$TRAVIS_BUILD_NUMBER/" >>sedcommand
cat sedcommand

sed -f sedcommand pages/downloads.txt >pages/downloads.html

