
name: Eval features

on:
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: New File
        run: |
          echo "Some test test" >${{ github.workspace }}/Support/test.txt
          ls -l ${{ github.workspace }}/Support

      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Test commit from eval workflow [skip ci]"
          git push origin master
